sudo: required
dist: xenial
git:
  depth: 1

language: php
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql
  - postgresql

env:
  matrix:
    - DB_DRIVER=pdo_mysql DB_USER=root
    - DB_DRIVER=pdo_pgsql DB_USER=phpunit DB_PASSWORD=phpunit
  global:
    - TRAVIS_SECURE_ENV_VARS=true
    - secure: "D85mhHqlhgIZExOQMJCp3oxiYYAPLm2N9by9C1dw/q/GNWsWRy3sdVsTALSkhwFRRR1JiU3a0C0ExxrsrwGQ/Nk6j5gmdQNRlJCeHZ6jiLzpsW+fkma/Kh29+gz4ZGHtqi1FzwAV7RhzSWMmVvbbKId2qsbGCR+sWpxpZ+48jifGBHq4+VDk+tpSXh2SFOi3VR8tGeEiaUqYm79fLKkrtCZjHf2mvzv0epJcPzqIZVXytpypoL4NB1rpPOBMDj9iQDpbEkVbD0yt4zE26m7GWVJADniOUa/ZsFiFEFKz9TioeP36QEfykYHXq6pSqAwh4GAePn4ceLkRvorH3llh+DxTJU2o6+RxH8640Db1B169ewxUoj9dFuMaaEvojOk+ZfNg3aE3RW0xF6WY1oYJYkSDtmfFoavIf8WH5HuaqeBcVYKPcRcCRw88NJoG7QRIOyKk2g7Xy9N1fInYm+AZnO+nc02GcwKzJ2izScW65GOt8ceLq8Sy+8NvrxrT1VgpqDGOWnAX3iF2cYJ3ECvUTyoBen8qRrobW+YuchbNtXmy2Afus7Jmn21TtCSX1ekyqO43jSQExrNZJINhA0R9i89Jz7qwsMQQwEjsq620awN/nlXYCxnvrRHLozbe2616IKge81OFgy2xc/Ebi2xwOuSTz6YM+/EG4eWRI5nxvHA="


before_install:
  # Set Coverage flag
  - export COVERAGE=0
  - if [[ "${TRAVIS_PHP_VERSION}" == "7.3" && "${DB_DRIVER}" == "pdo_mysql" ]]; then export COVERAGE=1; fi

  # Code Climate
  - if [[ ${COVERAGE} -eq 1  ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ ${COVERAGE} -eq 1  ]]; then chmod +x ./cc-test-reporter; fi
  - if [[ ${COVERAGE} -eq 1  ]]; then ./cc-test-reporter before-build; fi

  # Postgres
  - if [[ "${DB_DRIVER}" == "pdo_pgsql" ]]; then psql -c "CREATE DATABASE test_db;" -U postgres; fi
  - if [[ "${DB_DRIVER}" == "pdo_pgsql" ]]; then psql -c "CREATE USER phpunit WITH PASSWORD 'phpunit';" -U postgres; fi
  - if [[ "${DB_DRIVER}" == "pdo_pgsql" ]]; then psql -c "GRANT ALL PRIVILEGES ON DATABASE test_db to phpunit;" -U postgres; fi
  - if [[ "${DB_DRIVER}" == "pdo_pgsql" ]]; then sudo sed -i 's/trust/md5/g' /etc/postgresql/*/main/pg_hba.conf; fi
  - if [[ "${DB_DRIVER}" == "pdo_pgsql" ]]; then sudo /etc/init.d/postgresql restart; fi

  # Mysql
  - if [[ "${DB_DRIVER}" == "pdo_mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS test_db;"; fi
  - if [[ "${DB_DRIVER}" == "pdo_mysql" ]]; then mysql -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'"; fi

before_script:
  - composer install --no-interaction --prefer-source

script:
  - if [[ ${COVERAGE} -eq 1 ]]; then vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=clover.xml; fi
  - if [[ ${COVERAGE} -eq 0 ]]; then vendor/bin/phpunit --configuration phpunit.xml.dist --no-cover; fi

after_script:
  # Code Climate
  - if [[ ${COVERAGE} -eq 1 ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

  # Scrutinizer
  - if [[ ${COVERAGE} -eq 1 ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ ${COVERAGE} -eq 1 ]]; then test -f ocular.phar && php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
